mbta/screens-config-lib

lib/config/v2/gl_eink.ex

When we switch to Mercury screens, we will have the ability to play audio on E-Ink. First thing needed to get it working is to allow the screen config to hold audio. 
[Notion task](https://app.asana.com/0/1176097567827729/1205748798471858/f)

feat: Add audio to GlEink config.

---

lib/config/v2/pre_fare.ex
lib/config/v2/reconstructed_alert.ex

This PR adds a new struct for the `ReconstructedAlert` widget config. The new struct will take the existing stop ID as well as a new boolean that tells the `WidgetInstance` to make any takeover alert single screen instead. We will eventually pair this with the CR widget so the single screen alert is on the left screen and the CR widget is on the right screen.

tweak: Add new ReconstructedAlert widget config struct

---

.tool-versions
lib/config/screen.ex
lib/config/v2/busway.ex

Part of 📝 [Set up new app: backend stuff](https://app.asana.com/0/1185117109217413/1206730847640132)
This config was already here to support the `V2.Solari` "skeleton" that was set up in `screens` a few years back. For the initial setup it doesn't need any changes, but we know we want to call these "busway screens" now and renaming it earlier is probably better since nothing uses it yet.
Implications:
* **Screens:** I've already implemented an equivalent change there and will PR soon. If desired, we can hold off merging this until that PR is also approved.
* **Screenplay:** I can't find any references to `solari_v2` anywhere in Screenplay currently.

Rename `solari_v2` to `busway_v2`

---

lib/config/v2/departures/section.ex

fix: missing struct child

---

mix.exs

Prevents compilation error due to at least one config module deriving `Jason.Encoder`.
Version requirement should work with both Screens (which requires Jason `~> 1.0`) and Screenplay (`~> 1.4`).

chore: Add explicit Jason dep

---

lib/config/v2/departures/filters/route_directions.ex

These functions need to be explicitly defined for all keys that are not part of `children`.
This fixes encountering "An error occurred" when trying to change the config using the admin UI, if the config contains the new Sectional screens. Tested locally with a copy of the migrated Sectional config, and it now validates.

fix: missing `value_to_json` in `RouteDirections`

---

lib/config/v2/departures/layout.ex
lib/config/v2/departures/section.ex

These docs were written before the implementation was done on the `screens` side, and the actual behavior diverged slightly.

doc: correct descriptions of some section fields

---

lib/config/v2/audio.ex
lib/config/v2/busway.ex
lib/config/v2/gl_eink.ex
lib/config/v2/pre_fare.ex

This PR adds the `Audio` config to Sectionals. This will be used by screens to determine if the screen should play audio.

feat: Add audio config to Sectionals.

---

lib/config/screen.ex

The list of vendors we converted to atoms and the list of allowed vendors were out of sync. I simplified the `from_json` logic so it just converts the vendor into an atom. Any existing vendors set to `n/a` or empty strings will map to `:n_a`. All other unknown vendors will fail and we can fix as needed.

chore: Fix vendors

---

lib/config/v2/audio.ex
lib/config/v2/busway.ex
lib/config/v2/gl_eink.ex
lib/config/v2/pre_fare.ex

All audio config values (except the periodic readout offset for bus shelters) are currently identical across all screens of a given type, and we expect/want this to continue to be true. We can simplify by making these un-configurable and essentially embedding the config for each screen type in Screens, as is currently done for e.g. the readout interval.
This also adds one field, indicating whether to enable periodic audio readouts. We expect to need this for upcoming bus shelter screens that will have audio buttons.

feat: simplify audio configuration

---

lib/config/arrow.ex
lib/config/v2/blue_bikes/station.ex
lib/config/v2/departures/header.ex
lib/config/v2/elevator.ex
lib/config/v2/shuttle_bus_info.ex

Adding some new fields that will be needed when building out the "Current elevator closed" view on the widget.

chore: Add new fields to elevator widget

---

lib/config/v2/elevator.ex

There was one thing I missed in the design and another that was changed. 
- Screens will not be required to have accessible path images. If the image is `nil`, we will limit the layout to one page.
- There is a pulsating marker on the maps to indicate where the rider is currently located. My idea is this component will be positioned absolutely and we can configure the coordinates it should be displayed at. Essentially, `x` maps to `top` and `y` maps to `left`.

update: Elevator config

---

lib/config/screen.ex

`solari_large_v2` isn't used anywhere and can be removed.

chore: Remove unused screen type, solari_large_v2

---

.github/workflows/elixir.yml

Prompted by CI [currently failing](https://github.com/mbta/screens-config-lib/actions/runs/13639401980) because it uses a deprecated version of `actions/cache`.
Also removes a `-v2` cache prefix that had no purpose; this was there since the beginning of the repo and there was never a "v1".

ci: update Action versions

---

lib/config/departures/header.ex
lib/config/departures/section.ex

Adds two configuration options for wayfinding directions to be used in prefares.
- Boolean field that will disable departures fetching, included in a section's configuration
- Text field, passed in through the header, that will be used to show the wayfinding directions. This can be used regardless of the boolean field

[feat] Config option for Wayfinding only departures section

---

lib/config/departures/section.ex

- Grouping Type: :time or :departures and defaults to :time for now

Added grouping_type to section config

---

lib/config/screen/pre_fare.ex

Config changes for enabling departures on prefare screens. 
Departures now can be configured on PreFares, if null or sections is an empty array, it won't pass anything through and will continue to show the line map.

Enable Departures for PreFare screens

---

lib/config/footer.ex

This field could already be `nil` in practice given that is the default value, and we intend that this should be possible (e.g. to configure a footer on a screen not associated with a single stop), so document that in the typespec.

chore: footer `stop_id` can be null

---

lib/config/struct.ex
test/config/struct_test.exs

Adds the option for modules using `ScreensConfig.Struct` to define a `migrate_json/1` function which can transform the JSON before it is fully deserialized. The short-term motivation is to enable conveniently renaming the `stop_id` field in `ScreensConfig.Alerts` to `stop_ids`, since we would like to support multiple stop IDs here and the name should reflect that. But this provides a generic capability to do many kinds of backwards-incompatible JSON format "migration".

feat: JSON format migration in `Struct`

---

lib/config/arrow.ex
lib/config/departures/header.ex
lib/config/screen/elevator.ex

Atoms that exist only in typespecs are not always considered to "exist" at runtime; as a result, deserializing an `Arrow` would sometimes crash. Refactor this so the atoms do "exist" and the two places that use Arrows have a shared logic to deserialize them.

fix: already-existing-atom error with Arrows

---

lib/config/multi_stop_alerts.ex
lib/config/screen/bus_eink.ex

See #61 for the implementation of `migrate_json/1`, which this depends on.

feat: support multiple stop IDs in alerts config

---

.tool-versions
mix.exs

- NOTE: Being used and tested on https://github.com/mbta/screens/tree/deanshi/elixir_erlang_update
- compile showed no errors, no warnings
- credo/dialyzer worked no problems, mix test worked as well.

Update erlang to 27.3.4 and elixir to 1.17.3

---

lib/config/free_text/free_text.ex

**Asana task**: [Fix incorrect route pill for Cape Flyer](https://app.asana.com/1/15492006741476/project/1185117109217413/task/1210794505820587?focus=true)
Add CapeFlyer and it's associated color to the typespec for `route_pill` and `color` within `FreeText`

Add ferry and capeflyer to FreeText route pill types
